# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raPhGaYxAxFxOjVHkvuZZkrj7F95ZqZT
"""

import streamlit as st
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import base64

# Set page config
st.set_page_config(page_title="Higgs Boson and Field Visualization", layout="wide")

# Title
st.title("Higgs Boson and Higgs Field Visualization")

# Sidebar for particle selection
st.sidebar.header("Particle Selection")
particles = {
    "Electron": {"mass": 0.511, "color": "blue"},
    "Muon": {"mass": 105.7, "color": "green"},
    "Top Quark": {"mass": 172500, "color": "red"}
}
selected_particle = st.sidebar.selectbox("Select a particle", list(particles.keys()))

# Higgs Field Visualization
def higgs_field(particle_mass):
    x = np.random.randn(1000)
    y = np.random.randn(1000)
    z = np.random.randn(1000)

    particle_x = np.random.randn(1)
    particle_y = np.random.randn(1)
    particle_z = np.random.randn(1)

    fig = go.Figure(data=[
        go.Scatter3d(x=x, y=y, z=z, mode='markers', marker=dict(size=2, color='yellow', opacity=0.6),
                     name='Higgs Field'),
        go.Scatter3d(x=particle_x, y=particle_y, z=particle_z, mode='markers',
                     marker=dict(size=5 + particle_mass/10000, color=particles[selected_particle]['color']),
                     name=selected_particle)
    ])

    fig.update_layout(scene=dict(xaxis_title='X', yaxis_title='Y', zaxis_title='Z'),
                      width=700, height=700, margin=dict(r=20, b=10, l=10, t=10))

    return fig

# Higgs Boson Discovery Visualization
def higgs_discovery():
    steps = ['Proton Collision', 'Higgs Boson Created', 'Higgs Boson Decay', 'Decay Products Detected']

    fig = go.Figure()

    # Protons
    fig.add_trace(go.Scatter3d(x=[-2, 2], y=[0, 0], z=[0, 0], mode='markers',
                               marker=dict(size=8, color='blue'), name='Protons'))

    # Higgs Boson
    fig.add_trace(go.Scatter3d(x=[0], y=[0], z=[0], mode='markers',
                               marker=dict(size=12, color='yellow'), name='Higgs Boson'))

    # Decay Products
    fig.add_trace(go.Scatter3d(x=[0, 0], y=[1, -1], z=[0, 0], mode='markers',
                               marker=dict(size=6, color='green'), name='Decay Products'))

    fig.update_layout(scene=dict(xaxis_title='X', yaxis_title='Y', zaxis_title='Z'),
                      width=700, height=700, margin=dict(r=20, b=10, l=10, t=10),
                      updatemenus=[dict(type='buttons', showactive=False,
                                        buttons=[dict(label='Play',
                                                      method='animate',
                                                      args=[None, dict(frame=dict(duration=1000, redraw=True),
                                                                       fromcurrent=True,
                                                                       mode='immediate')])])])

    frames = [go.Frame(data=[go.Scatter3d(visible=True if i > 0 else False)
                             for i in range(4)],
                       name=f'frame{i}') for i in range(len(steps))]
    fig.frames = frames

    return fig

# Main content
tab1, tab2 = st.tabs(["Higgs Field", "Higgs Discovery"])

with tab1:
    st.header("Higgs Field Visualization")
    st.plotly_chart(higgs_field(particles[selected_particle]['mass']))
    st.write(f"Particle: {selected_particle}, Mass: {particles[selected_particle]['mass']} MeV/c²")
    st.write("The Higgs field permeates all space. Particles interact with this field, gaining mass. "
             "Heavier particles (larger spheres) move more slowly through the field, while lighter particles "
             "(smaller spheres) move faster. The yellow dots represent the Higgs field itself.")

with tab2:
    st.header("Higgs Boson Discovery Visualization")
    st.plotly_chart(higgs_discovery())
    st.write("This animation shows the process of Higgs boson discovery. Two protons collide at high energy, "
             "creating a Higgs boson (yellow). The Higgs boson then quickly decays into other particles (green), "
             "which are detected in particle accelerators like the Large Hadron Collider (LHC).")

# Generate downloadable files
def get_csv_download_link(df, filename):
    csv = df.to_csv(index=False)
    b64 = base64.b64encode(csv.encode()).decode()
    href = f'<a href="data:file/csv;base64,{b64}" download="{filename}">Download {filename}</a>'
    return href

# Sample data for downloads
particle_data = pd.DataFrame(
    [{"Particle": k, "Mass (MeV/c²)": v['mass']} for k, v in particles.items()]
)

higgs_data = pd.DataFrame({
    "Property": ["Mass", "Spin", "Parity", "Mean Lifetime"],
    "Value": ["125.10 ± 0.14 GeV/c²", "0", "+1", "1.56 × 10^-22 s"]
})

st.sidebar.markdown("## Downloadable Files")
st.sidebar.markdown(get_csv_download_link(particle_data, "particle_data.csv"), unsafe_allow_html=True)
st.sidebar.markdown(get_csv_download_link(higgs_data, "higgs_boson_data.csv"), unsafe_allow_html=True)

# Python script for download
python_script = """
import numpy as np
import matplotlib.pyplot as plt

def higgs_potential(phi, mu, lambda_):
    return mu**2 * phi**2 / 2 + lambda_ * phi**4 / 4

phi = np.linspace(-2, 2, 1000)
mu_squared = -1
lambda_ = 0.5

V = higgs_potential(phi, np.sqrt(abs(mu_squared)), lambda_)

plt.figure(figsize=(10, 6))
plt.plot(phi, V)
plt.title("Higgs Potential")
plt.xlabel("φ")
plt.ylabel("V(φ)")
plt.grid(True)
plt.show()
"""

st.sidebar.markdown("## Python Script")
st.sidebar.download_button(
    label="Download Python Script",
    data=python_script,
    file_name="higgs_potential.py",
    mime="text/plain"
)

# Add some extra information
st.sidebar.markdown("## Additional Resources")
st.sidebar.markdown("[CERN Higgs Boson FAQ](https://home.cern/science/physics/higgs-boson/faq)")
st.sidebar.markdown("[Nobel Prize in Physics 2013](https://www.nobelprize.org/prizes/physics/2013/summary/)")